// Auto-generated by LugoCorp's Argzilla
module.exports = function () {
    var argbox = { options: {}, flags: {}, args: [] };
    var params = process.argv;
    if (params[2] == "init") {
        argbox.command = "init";
        for (var a = 3; a < params.length; a++) {
            var param = params[a];
            throw new Error("Too many arguments provided");
        }
    }
    else {
        for (var a = 2; a < params.length; a++) {
            var param = params[a];
            if (param == "-o") {
                if (a < params.length - 1) {
                    argbox.options.out = params[++a];
                    continue;
                }
                else {
                    throw new Error("No value was provided for option \"-o\"");
                }
            }
            if (param == "-f") {
                if (a < params.length - 1) {
                    argbox.options["in"] = params[++a];
                    continue;
                }
                else {
                    throw new Error("No value was provided for option \"-f\"");
                }
            }
            if (param == "-l") {
                if (a < params.length - 1) {
                    argbox.options.lang = params[++a];
                    continue;
                }
                else {
                    throw new Error("No value was provided for option \"-l\"");
                }
            }
            if (param == "-p") {
                argbox.flags.print = true;
                continue;
            }
            if (param == "--print") {
                argbox.flags.print = true;
                continue;
            }
            throw new Error("Too many arguments provided");
        }
    }
    return argbox;
};
