// Autogenerated by LugoCorp's Argzilla
module.exports=function(argv){
	let result={flags:{},options:{},args:[]};
	for(var a=2;a<argv.length;a++){
		if(argv[a]=="-o"){
			if(a==argv.length-1) throw new Error("No value was given for option '-o'");
			result.options["out"]=argv[++a];
			continue;
		}
		if(argv[a]=="-f"){
			if(a==argv.length-1) throw new Error("No value was given for option '-f'");
			result.options["in"]=argv[++a];
			continue;
		}
		if(argv[a]=="-l"){
			if(a==argv.length-1) throw new Error("No value was given for option '-l'");
			result.options["lang"]=argv[++a];
			continue;
		}
		result.args.push(argv[a]);
	}
	if(result.args.length>1) throw new Error("Invalid number of parameters given");
	return result;
}