const validate=require("./validate.js");
const argparse=require("./argparse.js");
const swamp=require("../../swamp");
const fs=require("fs");

// Generates Swamp GAST
function generateAST(lang,config){
  let nodes=swamp.nodes;
  proc=[];

  // Get current element from argv
  proc.push(nodes.def_var("e",nodes.type("string")));
  proc.push(nodes.set_var("e",nodes.array_get(nodes.get_var("argv"),nodes.get_var("i"))));

  // Handle flag parameters from config
  for(var a=0;a<(config.flags || []).length;a++){
    let flag=config.flags[a];
    for(var b=0;b<(flag.names || []).length;b++) proc.push(nodes.if_stmt(
      nodes.eq(nodes.get_var("e"),nodes.value("string",flag.names[b])),[
        nodes.comment("set some field in a compsite type to a boolean true value (result.flags.${flag.label})"),
        nodes.cont_stmt()
      ]
    ));
  }

  // Handle option parameters from config
  for(var a=0;a<(config.options || []).length;a++){
    let option=config.options[a];
    for(var b=0;b<(option.names || []).length;b++) proc.push(nodes.if_stmt(
      nodes.eq(nodes.get_var("e"),nodes.value("string",option.names[b])),[
        nodes.if_stmt(
          nodes.eq(nodes.get_var("i"),nodes.sub(nodes.get_var("argc"),nodes.value("int",1))),
          nodes.comment("Throw an error here please")
        ),
        nodes.comment("set some field in a compsite type to a boolean true value (result.flags.${flag.label})"),
        nodes.cont_stmt()
      ]
    ));
  }

  // Tree root for GAST
  return [
    nodes.comment("This code was generated by Argzilla (brought to you by LugoCorp)"),
    nodes.def_func("argparse",nodes.type("int"),[
      nodes.def_var("argc",nodes.type("int")),
      nodes.def_var("argv",nodes.type("array",nodes.type("string")))
    ],[
      nodes.comment("create composite args type"),
      nodes.for_loop("i",nodes.value("int",0),nodes.get_var("argc"),nodes.value("int",1),proc),
      nodes.comment("return args data")
    ])
  ]
}

// Call argparse
let result=argparse(process.argv);
let config=fs.readFileSync(result.options.in || "argzilla.json").toString();
try{
  config=JSON.parse(config);
}catch(err){
  throw new Error("Invalid Argzilla config file given");
}
validate(config);

// Handle init
if(result.params.length && result.params[0]=="init"){
  console.log(`{\n\t"language":"node",\n\t"out":"argparse.js",\n\t"options":[],\n\t"flags":[]\n}`);
  process.exit(0);
}

// Write output
let lang=result.options.lang || config.language;
let GAST=generateAST(lang,config);
swamp.setAST(GAST);
let output=swamp.render(lang);
if(result.flags.print) console.log(output);
else fs.writeFileSync(result.options.out || config.out,output);
