#!/bin/bash

langs=("javascript" "ruby")

# Build the project
printf "Building..."
tsc 2> /dev/null
if [ "$?" != "0" ]; then
  printf "Build failed\n"
  exit 1
fi
printf "Build complete\n"

out="bin/argparse.txt"
configs=( $(ls tests) )
for config in "${configs[@]}"; do
  printf "\nTesting ${config}\n"
  for lang in "${langs[@]}"; do
    printf "${lang}: "
    node bin/index.js -l "$lang" -p > $out
    if [ "$?" == "0" ]; then
      printf "GENERATED, "
      if [ "$lang" == "javascript" ]; then
        nodejs "$out"
        [ "$?" == "0" ] && printf "RUNS" || printf "ERROR"
      elif [ "$lang" == "ruby" ]; then
        ruby "$out"
        [ "$?" == "0" ] && printf "RUNS" || printf "ERROR"
      else
        printf "UNKNOWN"
      fi
      printf "\n"
    else
      printf "ERROR\n"
    fi
  done
done
