# This code was generated by Argzilla (brought to you by LugoCorp)
def argparse argc,argv
	# create composite args type
	for i in 0..argc do
		e=nil
		e=argv[i]
		if (e=="-p") then
			# set some field in a compsite type to a boolean true value (result.flags.${flag.label})
			next
		end
		if (e=="--print") then
			# set some field in a compsite type to a boolean true value (result.flags.${flag.label})
			next
		end
		if (e=="-o") then
			if (i==(argc-1)) then
				# Throw an error here please
			end
			# set some field in a compsite type to a boolean true value (result.flags.${flag.label})
			next
		end
		if (e=="-f") then
			if (i==(argc-1)) then
				# Throw an error here please
			end
			# set some field in a compsite type to a boolean true value (result.flags.${flag.label})
			next
		end
		if (e=="-l") then
			if (i==(argc-1)) then
				# Throw an error here please
			end
			# set some field in a compsite type to a boolean true value (result.flags.${flag.label})
			next
		end
	end
	# return args data
end