// Auto-generated by LugoCorp's Argzilla
module.exports=function(){
	let argbox={options:{},flags:{},args:[]};
	let start=2;
	for(var a=start;a<process.argv.length;a++){
		let param=process.argv[a];
		if(param=="-o"){
			if(a<process.argv.length-1){
				argbox.options.out=process.argv[++a];
				continue;
			}else{
				throw new Error("No value was provided for option \"-o\"");
			}
		}
		if(param=="-f"){
			if(a<process.argv.length-1){
				argbox.options.in=process.argv[++a];
				continue;
			}else{
				throw new Error("No value was provided for option \"-f\"");
			}
		}
		if(param=="-l"){
			if(a<process.argv.length-1){
				argbox.options.lang=process.argv[++a];
				continue;
			}else{
				throw new Error("No value was provided for option \"-l\"");
			}
		}
		if(param=="-p"){
			argbox.flags.print=true;
			continue;
		}
		if(param=="--print"){
			argbox.flags.print=true;
			continue;
		}
		if(argbox.args.length==1){
			throw new Error("Too many arguments provided");
		}
		argbox.args.push(param);
	}
	return argbox;
}
