
let Strings={
  disclaimer:"Auto-generated by LugoCorp's Argzilla",
  errors:{
    missing_option:"ARGZILLA_MISSING_OPTION",
    too_many_args:"ARGZILLA_TOO_MANY_ARGS",
    too_few_args:"ARGZILLA_TOO_FEW_ARGS"
  }
};

export default Strings;
