
let Strings={
  disclaimer:"Auto-generated by LugoCorp's Argzilla",
  missing_option:label => `No value was provided for option \\\"${label}\\\"`,
  too_many_args:"Too many arguments provided",
  too_few_args:"Too few arguments provided",
};

export default Strings;
